codecov:
  require_ci_to_pass: false

coverage:
  status:
    project:
      default:
        target: auto
        threshold: 0.3%
        if_ci_failed: error
        only_pulls: false

    patch:
      default:
        target: auto
        threshold: 10%
