codecov:
  require_ci_to_pass: false

coverage:
  status:
    project:
      default:
        target: auto
        threshold: 3%
        informational: true

    patch:
      default:
        target: auto
        threshold: 25%
        informational: true
