issues:
  fix: true

  # Relax rules for tests
  exclude-rules:
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - dupl

      # Parsing logic has high cyclomatic complexity. This is okay.
    - path: pkg/importer/parser/ynab4/parse.go
      linters:
        - gocyclo
      text: "func `parseTransactions`"

      # Parsing logic has high cyclomatic complexity. This is okay.
    - path: pkg/importer/creator.go
      linters:
        - gocyclo
      text: "func `Create`"

    - path: pkg/models/envelope.go
      linters:
        - gocyclo
      text: "func `\\(Envelope\\).Balance`"

linters:
  enable:
    - gocyclo
    - godot
    # Disabled as the latest version - 0.4.0 from 2022-09-27 is not built with go 1.19 and
    # therefore disagrees with swag fmt about the formatting of the swagger comments.
    # See https://github.com/mvdan/gofumpt/issues/254
    # - gofumpt

    # Disabled since goimports reformats correct 1.19 doc comments
    # - goimports
    - govet
    - revive
    - whitespace
    - misspell

linters-settings:
  gofumpt:
    extra-rules: true
  gocyclo:
    min-complexity: 15

  godot:
    exclude:
      - "^ @[A-Za-z]+ "
