issues:
  fix: true

  # Relax rules for tests
  exclude-rules:
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - dupl
      # Parsing logic has high cyclomatic complexity. This is okay.
    - path: pkg/importer/parser/ynab4/parse.go
      linters:
        - gocyclo
      text: "func `parseTransactions`"

linters:
  enable:
    - gocyclo
    - godot
    - gofumpt
    - goimports
    - govet
    - revive
    - whitespace
    - misspell

linters-settings:
  gofumpt:
    lang-version: "1.19"
    extra-rules: true
  gocyclo:
    min-complexity: 15

  godot:
    exclude:
      - "^ @[A-Za-z]+ "
