issues:
  fix: true

linters:
  enable:
    - gocyclo
    - godot
    - gofumpt
    - goimports
    - govet
    - revive
    - whitespace
    - misspell

linters-settings:
  gofumpt:
    lang-version: "1.18"
    extra-rules: true

  godot:
    exclude:
      - "^ @[A-Za-z]+ "
