issues:
  fix: true

  # Relax rules for tests
  exclude-rules:
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - dupl

    - path: pkg/models/envelope.go
      linters:
        - gocyclo
      text: "func `\\(Envelope\\).Balance`"

    - path: pkg/importer/parser/ynab4/parse.go
      linters:
        - gocyclo
      text: "func `parseTransactions`"

linters:
  enable:
    - gocyclo
    - godot
    - gofumpt
    - goimports
    - govet
    - revive
    - whitespace
    - misspell

linters-settings:
  gofumpt:
    extra-rules: true
  gocyclo:
    min-complexity: 20

  godot:
    exclude:
      - "^\t+@[A-Za-z]+\t+"
