version: "2"
linters:
  enable:
    - misspell
    - revive
    - whitespace
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - dupl
          - errcheck
          - gocyclo
        path: _test\.go
      - linters:
          - gocyclo
        path: pkg/models/envelope.go
        text: func `\(Envelope\).Balance`
      - linters:
          - gocyclo
        path: pkg/importer/parser/ynab4/parse.go
        text: func `parseTransactions`
      - linters:
          - revive
        path: internal/types/month.go
        text: "var-naming: avoid meaningless package names"
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  fix: true
formatters:
  enable:
    - gofumpt
    - goimports
  settings:
    gofumpt:
      extra-rules: true
  exclusions:
    generated: lax
