builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -X github.com/envelope-zero/backend/v2/pkg/router.version={{.Version}}

archives:
  - replacements:
      amd64: x86_64

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  use: github
  groups:
    - title: Features
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 0

    - title: "Bug fixes"
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 1

    - title: Others
      order: 2

    - title: "Dependency updates"
      regexp: "^.*chore(deps):+.*$"
      order: 3

dockers:
  - dockerfile: Dockerfile.goreleaser
    image_templates:
      - "ghcr.io/envelope-zero/backend:{{ .Tag }}"
      - "ghcr.io/envelope-zero/backend:v{{ .Major }}"
      - "ghcr.io/envelope-zero/backend:v{{ .Major }}.{{ .Minor }}"
      - "ghcr.io/envelope-zero/backend:latest"
