builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -X github.com/envelope-zero/backend/v5/pkg/router.version={{.Version}}

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  use: github
  groups:
    - title: Features
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 0

    - title: "Bug fixes"
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 1

    - title: Others
      order: 2

    - title: "Dependency updates"
      regexp: "^.*chore(deps):+.*$"
      order: 3

kos:
  - repository: ghcr.io/envelope-zero/backend
    tags:
      - "{{ .Tag }}" # v{{ .Major}}.{{ .Minor }}.{{ .Patch }}
      - "v{{ .Major }}"
      - "v{{ .Major }}.{{ .Minor }}"
      - latest
    bare: true
    preserve_import_paths: false
    platforms:
      - linux/amd64
      - linux/arm64
    labels:
      org.opencontainers.image.created: "{{.Date}}"
      org.opencontainers.image.revision: "{{.FullCommit}}"
      org.opencontainers.image.title: "{{.ProjectName}}"
      org.opencontainers.image.version: "{{.Version}}"
