version: "3"

services:
  db:
    image: postgres:14.4-alpine
    restart: always
    environment:
      - POSTGRES_USER=ez
      - POSTGRES_PASSWORD=thisisunsafe
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data

  backend:
    build: .
    depends_on:
      - db
    ports:
      - 8080:8080
    environment:
      GIN_MODE: debug
      DB_HOST: db
      DB_USER: ez
      DB_PASSWORD: thisisunsafe
      DB_NAME: postgres

volumes:
  db:
