name: "go test"
description: "runs go tests"

runs:
  using: "composite"
  steps:
    - name: Check out repository
      uses: actions/checkout@v3.0.2

    - name: Set up go
      uses: actions/setup-go@v3.3.0
      with:
        # renovate: go-version
        go-version: 1.18.4

    - name: Run go tests
      shell: bash
      run: |
        go test ./... -race -covermode=atomic -coverprofile=coverage.out

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        files: coverage.out
