// Package docs GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/": {
            "options": {
                "description": "Returns an empty response with the HTTP Header \"allow\" set to the allowed HTTP verbs",
                "tags": [
                    "General"
                ],
                "summary": "Allowed HTTP verbs",
                "responses": {
                    "204": {
                        "description": ""
                    }
                }
            }
        },
        "/v1": {
            "options": {
                "description": "Returns an empty response with the HTTP Header \"allow\" set to the allowed HTTP verbs",
                "tags": [
                    "General"
                ],
                "summary": "Allowed HTTP verbs",
                "responses": {
                    "204": {
                        "description": ""
                    }
                }
            }
        },
        "/v1/budgets": {
            "get": {
                "description": "Returns list of budgets",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Budgets"
                ],
                "summary": "List all budgets",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.BudgetListResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/httputil.HTTPError"
                        }
                    }
                }
            },
            "post": {
                "description": "Creates a new budget",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Budgets"
                ],
                "summary": "Create a budget",
                "parameters": [
                    {
                        "description": "Budget",
                        "name": "budget",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.BudgetCreate"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/models.BudgetResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/httputil.HTTPError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/httputil.HTTPError"
                        }
                    }
                }
            },
            "options": {
                "description": "Returns an empty response with the HTTP Header \"allow\" set to the allowed HTTP verbs",
                "tags": [
                    "Budgets"
                ],
                "summary": "Allowed HTTP verbs",
                "responses": {
                    "204": {
                        "description": ""
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/httputil.HTTPError"
                        }
                    }
                }
            }
        },
        "/v1/budgets/{budgetId}": {
            "get": {
                "description": "Returns a specific budget",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Budgets"
                ],
                "summary": "Get a budget",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID of the budget",
                        "name": "budgetId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.BudgetResponse"
                        }
                    },
                    "404": {
                        "description": ""
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/httputil.HTTPError"
                        }
                    }
                }
            },
            "delete": {
                "description": "Deletes an existing budget",
                "tags": [
                    "Budgets"
                ],
                "summary": "Delete a budget",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID of the budget",
                        "name": "budgetId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": ""
                    },
                    "404": {
                        "description": ""
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/httputil.HTTPError"
                        }
                    }
                }
            },
            "options": {
                "description": "Returns an empty response with the HTTP Header \"allow\" set to the allowed HTTP verbs",
                "tags": [
                    "Budgets"
                ],
                "summary": "Allowed HTTP verbs",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID of the budget",
                        "name": "budgetId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": ""
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/httputil.HTTPError"
                        }
                    }
                }
            },
            "patch": {
                "description": "Update an existing budget",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Budgets"
                ],
                "summary": "Update a budget",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID of the budget",
                        "name": "budgetId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Budget",
                        "name": "budget",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.BudgetCreate"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.BudgetResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/httputil.HTTPError"
                        }
                    },
                    "404": {
                        "description": ""
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/httputil.HTTPError"
                        }
                    }
                }
            }
        },
        "/v1/budgets/{budgetId}/accounts": {
            "options": {
                "description": "Returns an empty response with the HTTP Header \"allow\" set to the allowed HTTP verbs",
                "tags": [
                    "Accounts"
                ],
                "summary": "Allowed HTTP verbs",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID of the budget",
                        "name": "budgetId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": ""
                    }
                }
            }
        },
        "/v1/budgets/{budgetId}/accounts/{accountId}": {
            "options": {
                "description": "Returns an empty response with the HTTP Header \"allow\" set to the allowed HTTP verbs",
                "tags": [
                    "Accounts"
                ],
                "summary": "Allowed HTTP verbs",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID of the budget",
                        "name": "budgetId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "ID of the account",
                        "name": "accountId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": ""
                    }
                }
            }
        },
        "/v1/budgets/{budgetId}/accounts/{accountId}/transactions": {
            "options": {
                "description": "Returns an empty response with the HTTP Header \"allow\" set to the allowed HTTP verbs",
                "tags": [
                    "Accounts"
                ],
                "summary": "Allowed HTTP verbs",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID of the budget",
                        "name": "budgetId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "ID of the account",
                        "name": "accountId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": ""
                    }
                }
            }
        },
        "/v1/budgets/{budgetId}/categories": {
            "options": {
                "description": "Returns an empty response with the HTTP Header \"allow\" set to the allowed HTTP verbs",
                "tags": [
                    "Categories"
                ],
                "summary": "Allowed HTTP verbs",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID of the budget",
                        "name": "budgetId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": ""
                    }
                }
            }
        },
        "/v1/budgets/{budgetId}/categories/{categoryId}": {
            "options": {
                "description": "Returns an empty response with the HTTP Header \"allow\" set to the allowed HTTP verbs",
                "tags": [
                    "Categories"
                ],
                "summary": "Allowed HTTP verbs",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID of the budget",
                        "name": "budgetId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "ID of the category",
                        "name": "categoryId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": ""
                    }
                }
            }
        },
        "/v1/budgets/{budgetId}/categories/{categoryId}/envelopes": {
            "options": {
                "description": "Returns an empty response with the HTTP Header \"allow\" set to the allowed HTTP verbs",
                "tags": [
                    "Envelopes"
                ],
                "summary": "Allowed HTTP verbs",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID of the budget",
                        "name": "budgetId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "ID of the category",
                        "name": "categoryId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": ""
                    }
                }
            }
        },
        "/v1/budgets/{budgetId}/categories/{categoryId}/envelopes/{envelopeId}": {
            "options": {
                "description": "Returns an empty response with the HTTP Header \"allow\" set to the allowed HTTP verbs",
                "tags": [
                    "Envelopes"
                ],
                "summary": "Allowed HTTP verbs",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID of the budget",
                        "name": "budgetId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "ID of the category",
                        "name": "categoryId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "ID of the envelope",
                        "name": "envelopeId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": ""
                    }
                }
            }
        },
        "/v1/budgets/{budgetId}/categories/{categoryId}/envelopes/{envelopeId}/allocations": {
            "options": {
                "description": "Returns an empty response with the HTTP Header \"allow\" set to the allowed HTTP verbs",
                "tags": [
                    "Allocations"
                ],
                "summary": "Allowed HTTP verbs",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID of the budget",
                        "name": "budgetId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "ID of the category",
                        "name": "categoryId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "ID of the envelope",
                        "name": "envelopeId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": ""
                    }
                }
            }
        },
        "/v1/budgets/{budgetId}/categories/{categoryId}/envelopes/{envelopeId}/allocations/{allocationId}": {
            "options": {
                "description": "Returns an empty response with the HTTP Header \"allow\" set to the allowed HTTP verbs",
                "tags": [
                    "Allocations"
                ],
                "summary": "Allowed HTTP verbs",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID of the budget",
                        "name": "budgetId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "ID of the category",
                        "name": "categoryId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "ID of the envelope",
                        "name": "envelopeId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "ID of the allocation",
                        "name": "allocationId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": ""
                    }
                }
            }
        },
        "/v1/budgets/{budgetId}/transactions": {
            "options": {
                "description": "Returns an empty response with the HTTP Header \"allow\" set to the allowed HTTP verbs",
                "tags": [
                    "Transactions"
                ],
                "summary": "Allowed HTTP verbs",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID of the budget",
                        "name": "budgetId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": ""
                    }
                }
            }
        },
        "/v1/budgets/{budgetId}/transactions/{transactionId}": {
            "options": {
                "description": "Returns an empty response with the HTTP Header \"allow\" set to the allowed HTTP verbs",
                "tags": [
                    "Transactions"
                ],
                "summary": "Allowed HTTP verbs",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID of the budget",
                        "name": "budgetId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "ID of the transaction",
                        "name": "transactionId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": ""
                    }
                }
            }
        },
        "/version": {
            "options": {
                "description": "Returns an empty response with the HTTP Header \"allow\" set to the allowed HTTP verbs",
                "tags": [
                    "General"
                ],
                "summary": "Allowed HTTP verbs",
                "responses": {
                    "204": {
                        "description": ""
                    }
                }
            }
        }
    },
    "definitions": {
        "gorm.DeletedAt": {
            "type": "object",
            "properties": {
                "time": {
                    "type": "string"
                },
                "valid": {
                    "description": "Valid is true if Time is not NULL",
                    "type": "boolean"
                }
            }
        },
        "httputil.HTTPError": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "An ID specified in the query string was not a valid uint64"
                }
            }
        },
        "models.Budget": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string",
                    "example": "2022-04-02T19:28:44.491514Z"
                },
                "currency": {
                    "type": "string",
                    "example": "€"
                },
                "deletedAt": {
                    "$ref": "#/definitions/gorm.DeletedAt"
                },
                "id": {
                    "type": "integer",
                    "format": "uint64",
                    "example": 42
                },
                "name": {
                    "type": "string",
                    "example": "My First Budget"
                },
                "note": {
                    "type": "string",
                    "example": "A description so I remember what this was for"
                },
                "updatedAt": {
                    "type": "string",
                    "example": "2022-04-17T20:14:01.048145Z"
                }
            }
        },
        "models.BudgetCreate": {
            "type": "object",
            "properties": {
                "currency": {
                    "type": "string",
                    "example": "€"
                },
                "name": {
                    "type": "string",
                    "example": "My First Budget"
                },
                "note": {
                    "type": "string",
                    "example": "A description so I remember what this was for"
                }
            }
        },
        "models.BudgetListResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Budget"
                    }
                }
            }
        },
        "models.BudgetResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/models.Budget"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
