name: go test & release

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  go-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.0.2

      - uses: actions/setup-go@v3
        with:
          # renovate: go-version
          go-version: 1.18.2

      - name: go test
        run: |
          go test -v ./... -race -covermode=atomic -coverprofile=coverage.out

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: coverage.out

  release:
    name: Release
    needs: go-test
    # We’re stull running in dry run, therefore don’t restrict to main yet
    # if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          install-only: true

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "lts/*"

      - name: Install dependencies
        run: npm install semantic-release @semantic-release/changelog @semantic-release/exec @semantic-release/git

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx -p @semantic-release/changelog -p @semantic-release/exec -p @semantic-release/git semantic-release
