name: "test"

on:
  push:
    branches-ignore:
      - main
    tags-ignore:
      - "v*"

  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3.3.0

      - name: go test
        uses: ./.github/actions/go-test
